### ISSUE TITLE
Please help me out

### ISSUE THREAD

**Issue by thakuranuj24** [Sayrix/discord-richpresence#1]
As as I know, I'm doing everything right, but I'm getting this error shown in the attachment. Please tell me what wrong I am doing and help me fix it. Thanks.
![IMG_20210427_231000](https://user-images.githubusercontent.com/73768891/116287329-e64e3d00-a7ad-11eb-87c0-dfd4a665ed3f.jpg)

**Comment by Sayrix** [comment]
you have discord launched at the same place where the script is launched?

**Comment by thakuranuj24** [comment]
Nope, thanks for helping, I'll try with discord launched this time.
